---
- name: Add repositories
  ansible.builtin.apt_repository:
    repo: "{{item}}"
    update_cache: yes
  loop: "{{ apt.repositories }}"
  when: "apt.repositories is defined"

- name: Install apt packages
  ansible.builtin.apt: 
    name: "{{ apt.packages }}"
  # loop: "{{ apt.packages }}"
  when: "apt.packages is defined"

- name: Install deb packages
  ansible.builtin.apt: 
    deb: "{{item}}"
  loop: "{{ apt.packages_deb }}"
  when: "apt.packages_deb is defined"

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes
