---
- name: Add repositories
  ansible.builtin.apt_repository:
    repo: "{{item}}"
    update_cache: yes
  with_items: "{{ ppa_repositories }}"

- name: Install apt packages
  ansible.builtin.apt: 
    name: "{{ apt_packages }}"
    update_cache: yes

- name: Install deb packages
  ansible.builtin.apt: 
    deb: "{{item}}"
  with_items:
    - "{{ deb_packages }}"

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes
