---
- hosts: localhost
  gather_facts: True
  collections:
  - community.general.flatpak

  pre_tasks:
    - include_vars: vars.yml
      tags: ["pre"]

    - name: Create the temporary directory
      tempfile:
        state: directory
        suffix: setup
      register: temp_dir_results
      tags: ["pre"]

    - set_fact:
        temp_dir={{ temp_dir_results.path }}
      tags: ["pre"]

  vars:
    desktop_mode: "{{ desktop | default(False) }}"
    laptop_mode: "{{ laptop | default(False) }}"
    chromebook_mode: "{{ chromebook | default(False) }}"
    home_dir: "{{ ansible_env.HOME }}"
    user: "{{ ansible_env.USER }}"
    
    apt_packages: >-
      {{ common_vars.apt_packages + (desktop_vars.apt_packages if (desktop_mode or laptop_mode) else [])
      + (laptop_vars.apt_packages if laptop_mode else [])
      + (chromebook_vars.apt_packages if chromebook_mode else []) }}
    deb_packages: >-
      {{ common_vars.deb_packages + (desktop_vars.deb_packages if (desktop_mode or laptop_mode) else [])
      + (laptop_vars.deb_packages if laptop_mode else [])
      + (chromebook_vars.deb_packages if chromebook_mode else []) }}
    ppa_repositories: >-
      {{ common_vars.ppa_repositories + (desktop_vars.ppa_repositories if (desktop_mode or laptop_mode) else [])
      + (laptop_vars.ppa_repositories if laptop_mode else [])
      + (chromebook_vars.ppa_repositories if chromebook_mode else []) }}
    snaps: >-
      {{ common_vars.snaps + (desktop_vars.snaps if (desktop_mode or laptop_mode) else [])
      + (laptop_vars.snaps if laptop_mode else [])
      + (chromebook_vars.snaps if chromebook_mode else []) }}
    flatpaks: >-
      {{ common_vars.flatpaks + (desktop_vars.flatpaks if (desktop_mode or laptop_mode) else [])
      + (laptop_vars.flatpaks if laptop_mode else [])
      + (chromebook_vars.flatpaks if chromebook_mode else []) }}


  roles:
    - role: shell/aliases
      tags: ["shell-aliases"]

    - role: shell/functions
      tags: ["shell-functions"]
    
    - role: shell/bashrc
      tags: ["shell-bashrc"]
  
    - role: asdf/install
      tags: ["asdf-install"]

    - role: apt-packages
      become: yes
      tags: ["apt-packages"]
    
    - role: snaps
      tags: ["snaps"]

    - role: dev/git-setup
      tags: ["git-setup"]

    - role: apps/docker
      become: yes
      tags: ["docker"]

    - role: apps/vscode
      when: desktop_mode or laptop_mode or chromebook_mode
      tags: ["vscode"]
      
    - role: apps/hyper
      when: desktop_mode or laptop_mode or chromebook_mode
      tags: ["hyper"]

    # # BROKEN
    # # Consider https://github.com/PeterMosmans/ansible-role-customize-gnome
    # # - role: gnome/extensions
    # #   when: gnome.extensions is defined

    # - role: gnome/theme
    #   when: gnome.theme is defined

    # - role: gnome/tweaks
    #   when: gnome.theme is defined

    - role: gnome/laptop
      when: laptop_mode

    - role: system/disable-intel-turbo
      when: laptop_mode
      tags: ["disable-turbo"]

  post_tasks:
    - name: Remove the temporary directory
      file:
        path: "{{ temp_dir }}"
        state: absent
    
