---
- hosts: localhost
  gather_facts: True
  collections:
  - community.general.flatpak

  pre_tasks:
    - include_vars: vars.yml
      tags: ["pre"]

    - name: Create the temporary directory
      tempfile:
        state: directory
        suffix: setup
      register: temp_dir_results
      tags: ["pre"]

    - set_fact:
        temp_dir={{ temp_dir_results.path }}
      tags: ["pre"]

  vars:
    desktop_mode: "{{ desktop | default(False) }}"
    laptop_mode: "{{ laptop | default(False) }}"
    chromebook_mode: "{{ chromebook | default(False) }}"
    home_dir: "{{ ansible_env.HOME }}"
    user: "{{ ansible_env.USER }}"
    
    apt_packages: >-
      {{ common_vars.apt_packages + (desktop_vars.apt_packages if (desktop_mode or laptop_mode) else [])
      + (laptop_vars.apt_packages if laptop_mode else [])
      + (chromebook_vars.apt_packages if chromebook_mode else []) }}
    deb_packages: >-
      {{ common_vars.deb_packages + (desktop_vars.deb_packages if (desktop_mode or laptop_mode) else [])
      + (laptop_vars.deb_packages if laptop_mode else [])
      + (chromebook_vars.deb_packages if chromebook_mode else []) }}
    gpg_keys: >-
      {{ common_vars.gpg_keys + (desktop_vars.gpg_keys if (desktop_mode or laptop_mode) else [])
      + (laptop_vars.gpg_keys if laptop_mode else [])
      + (chromebook_vars.gpg_keys if chromebook_mode else []) }}
    apt_repositories: >-
      {{ common_vars.apt_repositories + (desktop_vars.apt_repositories if (desktop_mode or laptop_mode) else [])
      + (laptop_vars.apt_repositories if laptop_mode else [])
      + (chromebook_vars.apt_repositories if chromebook_mode else []) }}
    snaps: >-
      {{ common_vars.snaps + (desktop_vars.snaps if (desktop_mode or laptop_mode) else [])
      + (laptop_vars.snaps if laptop_mode else [])
      + (chromebook_vars.snaps if chromebook_mode else []) }}
    flatpaks: >-
      {{ common_vars.flatpaks + (desktop_vars.flatpaks if (desktop_mode or laptop_mode) else [])
      + (laptop_vars.flatpaks if laptop_mode else [])
      + (chromebook_vars.flatpaks if chromebook_mode else []) }}


  roles:
    - role: apps/vscode
      when: desktop_mode or laptop_mode or chromebook_mode
      tags: ["vscode"]
      
    - role: apps/hyper
      when: desktop_mode or laptop_mode or chromebook_mode
      tags: ["hyper"]

    - role: shell/aliases
      tags: ["shell-aliases", "shell"]

    - role: shell/completion
      tags: ["shell-completion", "shell"]

    - role: shell/functions
      tags: ["shell-functions", "shell"]
    
    - role: asdf/install
      tags: ["asdf-install"]

    - role: apt-packages
      become: yes
      tags: ["apt-packages"]

    - role: apps/chrome-laptop-mod
      tags: ["chrome-laptop-mod"]
      when: laptop_mode
    
    - role: snaps
      tags: ["snaps"]

    - role: fonts
      tags: ["fonts"]

    - role: shell/starship
      tags: ["starship"]

    - role: flatpaks
      tags: ["flatpaks"]

    - role: shell/bashrc
      tags: ["shell-bashrc", "shell"]

    - role: dev/git-setup
      tags: ["git-setup"]

    - role: apps/docker
      become: TRUE
      tags: ["docker"]

    - role: gnome/extensions
      when: desktop_mode or laptop_mode
      tags: ["gnome-extensions"]

    - role: gnome/theme
      when: desktop_mode or laptop_mode
      tags: ["gnome-theme"]

    - role: gnome/settings
      when: desktop_mode or laptop_mode
      tags: ["gnome-settings"]

    - role: gnome/touchegg
      when: laptop_mode

    - role: system/disable-intel-turbo
      when: laptop_mode
      tags: ["disable-turbo"]

  post_tasks:
    - name: Remove the temporary directory
      file:
        path: "{{ temp_dir }}"
        state: absent
    
