---
- hosts: localhost
  gather_facts: False

  pre_tasks:
    - name: Create the temporary directory
      tempfile:
        state: directory
        suffix: setup
      register: temp_dir_results
    
    - set_fact:
        temp_dir={{ temp_dir_results.path }}

    - set_fact:
        home_dir={{ lookup('env', 'HOME') }}

    - set_fact:
        user={{ lookup('env', 'USER') }}

  roles:
    - role: shell/aliases
    
    - name: Common apt packages
      role: apt-packages
      become: yes
      apt: "{{ common.apt }}"
      when: "common.apt is defined"

    - name: Work apt packages
      role: apt-packages
      become: yes
      apt: "{{ work.apt }}"
      when: "work.apt is defined"
    
    - role: snaps
      become: yes
      when: snaps is defined

    - role: dev/git-setup
      when: dev.git is defined

    - role: apps/docker
      become: yes

    - role: dev/vscode
      when: gnome is defined or chomebook is defined
      
    - role: apps/hyper
      when: gnome is defined or chromebook is defined

    - role: gnome/extensions
      when: gnome.extensions is defined

    - role: gnome/theme
      when: gnome.theme is defined

  post_tasks:
    - name: Remove the temporary directory
      file:
        path: "{{ temp_dir }}"
        state: absent
    
