---
- name: Install Hyper
  become: yes
  ansible.builtin.apt:
    deb: https://releases.hyper.is/download/deb
    state: present

- name: Ansible check directory exists example.
  become: yes
  stat:
    path: "{{ home_dir }}/.hyper_plugins/local/hyper-cobalt-theme"
  register: extension_dir

- name: Download custom material theme
  become: yes
  ansible.builtin.git:
    repo: 'https://github.com/laidbackware/hyper-cobalt-theme.git'
    dest: "{{ home_dir }}/.hyper_plugins/local/hyper-cobalt-theme"
  when: not extension_dir.stat.exists

- name: Copy hyper config
  copy:
    src: .hyper.js
    dest: "{{ home_dir }}/.hyper.js"