---
- name: Install Snaps
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | default(false) }}"
  loop: "{{ snaps }}"
  become: true

# This hack copies system fonts to ~/.local/share/fonts for snaps
- name: Font hack
  shell: "for i in ls /etc/fonts/conf.d/*.conf ; do ln -s $i ~/.local/share/fonts/ ; done"