---

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Adding flatpaks
  community.general.flatpak:
    name: "{{ item.name }}"
    state: present
    method: user
  with_items: "{{flatpaks}}"