---

- name: Creates directory
  ansible.builtin.file:
    path: "{{ home_dir }}/.local/share/fonts"
    state: directory

- name: Install Fonts
  ansible.builtin.include_tasks: download-font.yml
  vars:
    github_user: "{{ item.github_user }}"
    github_repo: "{{ item.github_repo }}"
    file_name: "{{ item.file_name }}"
  with_items: "{{ common_vars.fonts }}"

- name: Update font cache
  ansible.builtin.command: fc-cache -fv